Models/ErrorViewModel.cs
using System;

namespace CalculatorApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/CalcController.cs
using Microsoft.AspNetCore.Mvc;
using System;

namespace CalculatorApp.Controllers
{
    public class CalcController : Controller
    {
        [HttpGet]
        public ActionResult Squareroot()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Squareroot(string firstNumber, string secondNumber)
        {
            try{
            double numberOne = double.Parse(firstNumber);
            double numberTwo = double.Parse(secondNumber);
            double fNumberSqrt = Math.Sqrt(numberOne);
            double sNumberSqrt = Math.Sqrt(numberTwo);
            ViewBag.NumberOne = numberOne;
            ViewBag.NumberTwo = numberTwo;
            ViewBag.FNumberSqrt = fNumberSqrt;
            ViewBag.SNumberSqrt = sNumberSqrt;
            }
            catch(Exception e)
            {
                Console.WriteLine(e.Message);
            }

            return View();
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using CalculatorApp.Models;

namespace CalculatorApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult NewPage()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Calc/Squareroot.cshtml
@{
    ViewData["Title"] = "Root | Finder";
}
<div class="text-center">
    <h1 class="display-0">The SquareRoot Calculator</h1>
</div>

       @if(ViewBag.FNumberSqrt > ViewBag.SNumberSqrt)
        {
            <div>
            <p>The number @ViewBag.NumberOne with square root 
                @ViewBag.FNumberSqrt has a higher square root than
                the number @ViewBag.NumberTwo with square root
                @ViewBag.SNumberSqrt
            </p>
            </div>
        }
        else if(ViewBag.FNumberSqrt < ViewBag.SNumberSqrt)
        {
            <div>
            <p>The number @ViewBag.NumberTwo with square root 
                @ViewBag.SNumberSqrt has a higher square root than
                the number @ViewBag.NumberOne with square root
                @ViewBag.FNumberSqrt
            </p>
            </div>
        }
        else if(ViewBag.FNumberSqrt == ViewBag.SNumberSqrt)
        {
            <div>
            <p>
                The Square root of the given numbers are the same.
                Please, enter another value
            </p>
            </div>
        }
        else if(ViewBag.NumberOne <= 0 || ViewBag.NumberTwo <=0)
        {
            <div>
            <p>
                ERROR!!!<br/>
                You entered a negative number, TRY AGAIN
            </p>
            </div>
        }
<div>
    <form asp-controller="calc" asp-action="Squareroot" method="POST">
        <input type="number" placeholder="First Number" name="firstNumber"/>
        <input type="number" placeholder="Second Number" name="secondNumber"/>
        <button type="submit">Submit</button>
    </form>
</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Home/NewPage.cshtml
@{
    ViewData["Title"] = "New Page";
}
<h1>@ViewData["Title"]</h1>

<p>Hey there, I have successfully created a page</p>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CalculatorApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CalculatorApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Calc" asp-action="Squareroot">SquareRootCalc</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - CalculatorApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>